### PR TITLE
Importing and exporting for .scn files

### PR DESCRIPTION
**Pull request by lalalune**

### CODE REVIEW

**Comment by amnaarshed4224** [comment]
Issues:
1-While trying to build the project using "npm run dev" this warning appears in the console. But the project get compiled successfully.

compile err

2-While making an empty project this errors appear

cors 3
cors1
cors2

3-This error appears while trying to import a scn

err while importin project
err while importing scn

4-This error pops up when the model url is tried to change.

model urll err

I was unable to test rest of the features due to multiple errors. The scene export seems to work fine. Sketchfab doesn't loads anything. Most of these errors are there in master too but i am putting them here so that they can be fixed here.

**Comment by pankaj2k9** [comment]
> Issues: 1-While trying to build the project using "npm run dev" this warning appears in the console. But the project get compiled successfully.
> 
> compile err
> 
> 2-While making an empty project this errors appear cors1 cors2 cors 3
> 
> 3-This error appears while trying to import a scn
> 
> err while importin project err while importing scn
> 
> 4-This error pops up when the model url is tried to change.
> 
> model urll err
> 
> I was unable to test rest of the features due to multiple errors. The scene export seems to work fine. Sketchfab doesn't loads anything. Most of these errors are there in master too but i am putting them here so that they can be fixed here.

1 and 2 for cert issue, you need to install selfsigned perfectlly. Make sure yarn install and then npm run dev.

**Comment by pankaj2k9** [comment]
1 and 2 for cert issue, you need to install selfsigned perfectlly. Make sure yarn install and then npm run dev.

**Comment by pankaj2k9** [comment]
For 3 . Can you give me the scene that you tried to upload?
For 4. I am trying to add cors anywhere.

**Comment by alisaad673** [comment]
for 3- I was trying to import the grid.scn from webaverse app

I am getting this error while trying to compile the repo
errrrcert

**Comment by pankaj2k9** [comment]
**In package.json file there was a dependency**: _"three": "github:MozillaReality/three.js.git#0f9b0024725f0dd917caa54c2934a4ba1fc12c4f",_
You need to make sure it is properlly downloaded, if not then you need to manually donwload the repo then add it node_modules three.js folder.

**Comment by alisaad673** [comment]
This PR seems to solve the import and export of .scn files. But there are certain limitations to the Importing and exporting format of the .scn files

1-The Cors url needs to be added in the exported .scn from the editor at the start of each start-url to make the scn work in webaverse app.
2-Similarly to import the scn back into editor we need to remove the cors-url from the start urls to make it work.
3-We can not import the general scenes that we have right now in webaverse in the current format as the other Editor related objects wont be usable then.
4-The hemisphere light isn't working right now
5-The sketcfab objects are not workable right now as they don't have the glb extension to download them. As the dev said we can make it work later on through api.

As far as the PR is concerned it seems to serve its purpose of import and export of scenes. I will create issues for other editor related issues seperately.

**Comment by lalalune** [comment]
The PR comes from our main repo. We're going to start pushing commits and PRs directly into this repo, as per permission, so that we can keep them separate.

The importing and exporting works and certainly doesn't harm anything.

@kimenyikevin has integrated Discord login so that we can integrate with Webaverse inventory, which is the next step, so we can directly load,save and edit .scn files into a user's wallet.

**Comment by alisaad673** [comment]
Merging the PR so that a working build is there for editaverse.

**Pull request merged**
